//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarinaRemake.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dock
    {
        public Dock()
        {
            this.Slips = new HashSet<Slip>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public bool WaterService { get; set; }
        public bool ElectricalService { get; set; }
    
        public virtual ICollection<Slip> Slips { get; set; }
    }
}
